### ISSUE TITLE
Getting runtime crash in release build

### ISSUE THREAD

**Issue by shruti-vig** [tony19/named-regexp#13]
java.lang.RuntimeException: An error occured while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:304)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/code/regexp/Pattern;
        at com.android.beewisesdk.PopulateMessagesAsyncTask.populate_messages(BW.java:880)
        at com.android.beewisesdk.PopulateMessagesAsyncTask.doInBackground(BW.java:320)
        at com.android.beewisesdk.PopulateMessagesAsyncTask.doInBackground(BW.java:251)
        at android.os.AsyncTask$2.call(AsyncTask.java:292)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
        at java.lang.Thread.run(Thread.java:818) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.code.regexp.Pattern" on path: DexPathList[[zip file "/data/app/com.citrus.citruspay-1/base.apk"],nativeLibraryDirectories=[/data/app/com.citrus.citruspay-1/lib/arm, /vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)

**Comment by tony19** [comment]
Please provide steps to reproduce the issue.

**Comment by shruti-vig** [comment]
I upgraded gradle and studio and it started giving runtime exceptions. Tried clean, build, invalidate cache, restarting studio, deleting build files, etc.
Finally have managed to fix this by building Jar and adding it in project.

**Comment by tony19** [comment]
Seems like a known issue with Android Studio. Try disabling and enabling Instant Run as recommended in this SO post .
